### PR TITLE
Return false on permission denied

### PR DESCRIPTION
**Pull request by rahuldange09**
Hello,
Thanks for this package.
I have made the following changes
- **Return false when permission is denied in Android**:  As on the flutter side, there is no way to understand whether it Called a Phone number or not, in case of permission is denied. So it will return false in permission denied case. Which will help at flutter side to open it in dialer or do something with it.
- **Also removed unnecessary platformVersion method as it is not needed.**

I hope you approve these changes.

Thank you

### CODE REVIEW

**Comment by rahuldange09** [comment]
Added another fix in the latest commit.
To avoid conflicting with other plugins "permissionResult" which were resulting in the crash of the app.
Like I was using "permission_handler" and when I used to deny permission for that plugin it was resulting in a crash because of not checking with "requestCode" in this plugin.

**Comment by rahuldange09** [comment]
@yanisalfian Any updates on this?

**Comment by yanisalfian** [comment]
Hi @rahuldange09 

Sorry for the late reply. Has been busy these days. 

I see no problem in your PR. I will merge it and publish it to pub.dev.

**Comment by rahuldange09** [comment]
Great!
Thank you :)

**Pull request merged**
